"""add_user_profile_fields

Revision ID: 687edc95c240
Revises: fix_null_usernames
Create Date: 2025-07-29 09:55:58.381798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687edc95c240'
down_revision: Union[str, Sequence[str], None] = 'fix_null_usernames'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fitness_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hiking_experience_years', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'hiking_experience_years')
    op.drop_column('users', 'fitness_level')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
