name: Deploy to Droplet

on:
  push:
    paths:
      - 'back/AIgyr/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Deploy to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          cd ${{ secrets.DROPLET_PATH }}
          git fetch origin main
          git reset --hard origin/main
          docker compose down
          docker compose up -d --build
        EOF
