name: Deploy to DigitalOcean

on:
  push:
    paths:
      - 'back/AIgyr/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Droplet via SSH with Password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASS }}
        port: 22
        script: |
          cd back/back/AIgyr
          git pull
          docker compose up --build -d
